# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resv', '0003_reservoir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservoir',
        ),
    ]
