# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 09:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resv', '0005_reservoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='reservoir',
            name='long',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9),
        ),
    ]
