# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resv', '0006_auto_20170822_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='maxLevel',
            field=models.FloatField(default=0.0),
        ),
    ]
